development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:15ed1dc98a9ed971ccb077575b0e4045@spinyfin.redistogo.com:9942/
  channel_prefix: pictionary_production
